; Main pmodelib include
;  By Peter Johnson, 1999-2000
;
; $Id: lib291.inc,v 1.7 2001/03/02 08:03:39 pete Exp $

%include "myC32.mac"

%include "constant.inc"
%include "globals.inc"
%include "dma.inc"
%include "dpmi_int.inc"
%include "dpmi_mem.inc"
%include "filefunc.inc"
%include "gfxfiles.inc"
%include "int_wrap.inc"
%include "lib_load.inc"
%include "misc.inc"
%include "netbios.inc"
%include "rmcbwrap.inc"
%include "textmode.inc"
%include "vbeaf.inc"
