; Main pmodelib include
;  By Peter Johnson, 1999-2000
;
; $Id: lib291.inc,v 1.6 2000/12/14 07:52:21 pete Exp $

%include "myC32.mac"

%include "constant.inc"
%include "globals.inc"
%include "dma.inc"
%include "dpmi_int.inc"
%include "dpmi_mem.inc"
%include "filefunc.inc"
%include "graphics.inc"
%include "gfxfiles.inc"
%include "int_wrap.inc"
%include "lib_load.inc"
%include "misc.inc"
%include "netbios.inc"
%include "rmcbwrap.inc"
%include "textmode.inc"
%include "vesa.inc"
